name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  appEnv: prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - projectName: devnotes-blog-pl
            site: pl
          - projectName: devnotes-blog-en
            site: en

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Setup app env
        id: setup-app-env
        if: ${{ github.ref_name != 'main' }}
        run: |
          echo "appEnv=test" >> "$GITHUB_ENV";

      - name: Setup build cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('app/**', 'assets/**', '**.[jt]s', '**.[jt]sx', '**.json') }}

      - name: Build
        run: yarn build
        env:
          SITE: ${{ matrix.site }}
          APP_ENV: ${{ env.appEnv }}

      - uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ matrix.projectName }}
          directory: out
